01-06 - 01-12

diff --git a/gtkspell2/patches/enchant2.patch b/gtkspell2/patches/enchant2.patch
--- a/gtkspell2/patches/enchant2.patch
+++ b/gtkspell2/patches/enchant2.patch
@@ -1,6 +1,105 @@
+diff -Naur orig/configure patched/configure
+--- orig/configure	2009-10-23 04:57:15.000000000 +0200
++++ patched/configure	2020-03-26 09:55:37.963558886 +0100
+@@ -2584,7 +2584,7 @@
+ ac_config_headers="$ac_config_headers config.h"
+ 
+ 
+-SPELLER_LIB=-lenchant
++SPELLER_LIB=-lenchant-2
+ 
+ 
+ GTKSPELL_PACKAGES=gtk+-2.0
+@@ -2715,12 +2715,12 @@
+         pkg_cv_GTKSPELL_CFLAGS="$GTKSPELL_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\$GTKSPELL_PACKAGES enchant >= 0.4.0 \"") >&5
+-  ($PKG_CONFIG --exists --print-errors "$GTKSPELL_PACKAGES enchant >= 0.4.0 ") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 \"") >&5
++  ($PKG_CONFIG --exists --print-errors "$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 ") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GTKSPELL_CFLAGS=`$PKG_CONFIG --cflags "$GTKSPELL_PACKAGES enchant >= 0.4.0 " 2>/dev/null`
++  pkg_cv_GTKSPELL_CFLAGS=`$PKG_CONFIG --cflags "$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 " 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -2733,12 +2733,12 @@
+         pkg_cv_GTKSPELL_LIBS="$GTKSPELL_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\$GTKSPELL_PACKAGES enchant >= 0.4.0 \"") >&5
+-  ($PKG_CONFIG --exists --print-errors "$GTKSPELL_PACKAGES enchant >= 0.4.0 ") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 \"") >&5
++  ($PKG_CONFIG --exists --print-errors "$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 ") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GTKSPELL_LIBS=`$PKG_CONFIG --libs "$GTKSPELL_PACKAGES enchant >= 0.4.0 " 2>/dev/null`
++  pkg_cv_GTKSPELL_LIBS=`$PKG_CONFIG --libs "$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 " 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -2757,14 +2757,14 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        GTKSPELL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "$GTKSPELL_PACKAGES enchant >= 0.4.0 "`
++	        GTKSPELL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 "`
+         else
+-	        GTKSPELL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "$GTKSPELL_PACKAGES enchant >= 0.4.0 "`
++	        GTKSPELL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "$GTKSPELL_PACKAGES enchant-2 >= 2.0.0 "`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$GTKSPELL_PKG_ERRORS" >&5
+ 
+-	{ { $as_echo "$as_me:$LINENO: error: Package requirements ($GTKSPELL_PACKAGES enchant >= 0.4.0 ) were not met:
++	{ { $as_echo "$as_me:$LINENO: error: Package requirements ($GTKSPELL_PACKAGES enchant-2 >= 2.0.0 ) were not met:
+ 
+ $GTKSPELL_PKG_ERRORS
+ 
+@@ -2775,7 +2775,7 @@
+ and GTKSPELL_LIBS to avoid the need to call pkg-config.
+ See the pkg-config man page for more details.
+ " >&5
+-$as_echo "$as_me: error: Package requirements ($GTKSPELL_PACKAGES enchant >= 0.4.0 ) were not met:
++$as_echo "$as_me: error: Package requirements ($GTKSPELL_PACKAGES enchant-2 >= 2.0.0 ) were not met:
+ 
+ $GTKSPELL_PKG_ERRORS
+ 
+@@ -14948,7 +14948,8 @@
+ if test -n "$CONFIG_FILES"; then
+ 
+ 
+-ac_cr=''
++ac_cr='
++'
+ ac_cs_awk_cr=`$AWK 'BEGIN { print "a\rb" }' </dev/null 2>/dev/null`
+ if test "$ac_cs_awk_cr" = "a${ac_cr}b"; then
+   ac_cs_awk_cr='\\r'
+diff -Naur orig/configure.ac patched/configure.ac
+--- orig/configure.ac	2009-10-23 04:52:31.000000000 +0200
++++ patched/configure.ac	2020-03-26 09:55:45.507669421 +0100
+@@ -12,12 +12,12 @@
+ AM_INIT_AUTOMAKE(AC_PACKAGE_NAME, AC_PACKAGE_VERSION)
+ AC_CONFIG_HEADERS([config.h])
+ 
+-SPELLER_LIB=-lenchant
++SPELLER_LIB=-lenchant-2
+       
+ AC_SUBST(SPELLER_LIB)
+ GTKSPELL_PACKAGES=gtk+-2.0
+ AC_SUBST(GTKSPELL_PACKAGES)
+-PKG_CHECK_MODULES(GTKSPELL, $GTKSPELL_PACKAGES enchant >= 0.4.0 )
++PKG_CHECK_MODULES(GTKSPELL, $GTKSPELL_PACKAGES enchant-2 >= 2.0.0 )
+ AC_SUBST(GTKSPELL_CFLAGS)
+ AC_SUBST(GTKSPELL_LIBS)
+ 
 diff -Naur orig/gtkspell/gtkspell.c patched/gtkspell/gtkspell.c
 --- orig/gtkspell/gtkspell.c	2009-10-09 21:01:47.000000000 +0200
-+++ patched/gtkspell/gtkspell.c	2018-02-14 11:49:45.350065935 +0100
++++ patched/gtkspell/gtkspell.c	2020-03-26 09:50:25.758950942 +0100
 @@ -277,7 +277,7 @@
  	get_word_extents_from_mark(spell->buffer, &start, &end, spell->mark_click);
  	word = gtk_text_buffer_get_text(spell->buffer, &start, &end, FALSE);
