upd: chromium (a rust llvm 19-et igényel, amivel viszont nem fordul a mostani mesa)

diff --git a/chromium/compile b/chromium/compile
--- a/chromium/compile
+++ b/chromium/compile
@@ -4,17 +4,14 @@
 
 freespace=$((`stat -f -c "%a" .`*`stat -f -c "%s" .`/(1024*1024*1024)))
 
-rm -Rf third_party/llvm* # 1400M
-rm -Rf third_party/rust-src # 3600M
+rm -Rf third_party/llvm* # 1.9G
+rm -Rf third_party/rust-src # 4.4G
+rm -Rf third_party/rust-toolchain # 1.3G
+rm -Rf third_party/instrumented_libs # 2.2G
 
-if [ -d third_party/rust-src -a -d third_party/llvm ]; then
-    if [ $freespace -lt 23 ]; then
-	    echo "At least 23 GB free space is required!"
-	    exit 1
-	fi
-elif [ $freespace -lt 18 ]; then
-	echo "At least 18 GB free space is required!"
-	exit 1
+if [ $freespace -lt 25 ]; then
+    echo "At least 25 GB free space is required!"
+    exit 1
 fi
 
 procs=$(grep ^processor /proc/cpuinfo | wc -l)
@@ -33,9 +30,6 @@ export CCACHE_SLOPPINESS=time_macros
 _clang_version=$(clang --version | grep -m1 version | sed 's/.* \([0-9]\+\).*/\1/')
 # enable rust nightly features
 export RUSTC_BOOTSTRAP=1
-# qt5, qt6 path
-export PATH="$PATH:/usr/lib/qt5/bin"
-export PATH="$PATH:/usr/lib/qt6/libexec"
 
 _flags=("
 custom_toolchain=\"//build/toolchain/linux/unbundle:default\"
@@ -49,9 +43,9 @@ clang_base_path=\"/usr\"
 clang_use_chrome_plugins=false
 clang_version=\"$_clang_version\"
 rust_sysroot_absolute=\"/usr\"
+rust_bindgen_root=\"/usr\"
 rustc_version=\"$(rustc --version)\"
 chrome_pgo_phase=0
-use_gold=false
 use_lld=true
 is_clang=true
 is_cfi=false
@@ -78,7 +72,6 @@ use_system_libjpeg=true
 use_system_libpng=true
 use_qt=true
 use_qt6=true
-moc_qt5_path=\"/usr/lib/qt5/bin/\"
 moc_qt6_path=\"/usr/lib/qt6/libexec/\"
 gtk_version=4
 icu_use_data_file=false
@@ -89,7 +82,7 @@ _syslibs=(
 	fontconfig
 	freetype
 	harfbuzz-ng
-#	icu
+	icu
 	libdrm
 	libevent
 	libjpeg
@@ -121,9 +114,10 @@ sed "s|//third_party/usb_ids/usb.ids|/usr/share/hwdata/usb.ids|g" -i services/de
 
 python3 build/linux/unbundle/replace_gn_files.py --system-libraries "${_syslibs[@]}"
 
-# node
-mkdir -p third_party/node/linux/node-linux-x64/bin
-ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/node
+# Link to system tools required by the build
+rm third_party/node/linux/node-linux-x64/bin/node # precompiled binary
+ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/
+ln -s /usr/bin/java third_party/jdk/current/bin/
 
 # gn a buildhoz
 # tools/gn/bootstrap/bootstrap.py --build-path=$outdir --gn-gen-args=" ${_flags[@]} "
